//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 11:25:34 PM IST 
//


package com.rxp.realcontrol.api;

import java.util.List;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}baseEntity">
 *       &lt;sequence>
 *         &lt;element name="accountName" type="{}accountName"/>
 *         &lt;element name="accountType" type="{}accountType"/>
 *         &lt;element name="bankName" type="{}bankName"/>
 *         &lt;element name="ccp" type="{}accountCcps" minOccurs="0"/>
 *         &lt;element name="legalIps" type="{}legalIps" minOccurs="0"/>
 *         &lt;element name="legalReferers" type="{}legalReferers" minOccurs="0"/>
 *         &lt;element name="returnUrls" type="{}returnUrls" minOccurs="0"/>
 *         &lt;element ref="{}merchantDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Root
public class Account {

    @Element(required = false)
    public String accountName;
    
    @Element(required = false)
    public String accountType;
    
    @Element(required = false)
    public String bankName;
    
    @Element(required = false)
    public String ccp;
    
    @ElementList(required=false)
    public List<LegalIp> legalIps;
    
    @ElementList(required=false)
    public List<LegalReferer> legalReferers;
    
    @ElementList(required=false)
    public List<ReturnUrl> returnUrls;
    
    @ElementList(required=false)
    public List<MerchantDetail> merchantDetails;

}
