//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 11:25:34 PM IST 
//


package com.rxp.realcontrol.api;

import java.util.List;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}baseEntity">
 *       &lt;sequence>
 *         &lt;element name="id" type="{}clientId"/>
 *         &lt;element name="defaultAccount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="status" type="{}clientStatus"/>
 *         &lt;element name="webAddress" type="{}url" minOccurs="0"/>
 *         &lt;element name="email" type="{}email" minOccurs="0"/>
 *         &lt;element name="companyName" type="{}companyName" minOccurs="0"/>
 *         &lt;element name="tradingAs" type="{}companyName" minOccurs="0"/>
 *         &lt;element name="address1" type="{}addressLine" minOccurs="0"/>
 *         &lt;element name="address2" type="{}addressLine" minOccurs="0"/>
 *         &lt;element name="city" type="{}city" minOccurs="0"/>
 *         &lt;element name="country" type="{}address-country-code" minOccurs="0"/>
 *         &lt;element name="phone" type="{}phoneNumber" minOccurs="0"/>
 *         &lt;element name="fax" type="{}phoneNumber" minOccurs="0"/>
 *         &lt;element name="portfolio" type="{}portfolio" minOccurs="0"/>
 *         &lt;element ref="{}allowedTransactionTypes"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Root
public class Client {

	@Element
    public String id;
	
	@Element(required=false)
    public int defaultAccount;
    
	@Element
	public String status;
	
	@Element(required=false)
    public String webAddress;
    
	@Element(required=false)
	public String email;
    
	@Element(required=false)
	public String companyName;
    
	@Element(required=false)
	public String tradingAs;
    
	@Element(required=false)
	public String address1;
    
	@Element(required=false)
	public String address2;
    
	@Element(required=false)
	public String city;
    
	@Element(required=false)
	public String country;
    
	@Element(required=false)
	public String phone;
	
	@Element(required=false)
	public String fax;
    
	@Element(required=false)
	public String portfolio;
    
	@ElementList
	public List<Type> allowedTransactionTypes;

} 